type: cifar
lr: 0.05 
momentum: 0.9
decay: 0.0005
batch_size: 50
test_batch_size: 50
epochs: 1
internal_epochs: 5 
binary_cls: true

withDP: true
max_clip_norm: 1.0 
noise_multiplier: 8
delta: 0.00001
no_models: 10
number_of_total_participants: 10
pre_path: saved_models/cifar_insdp
n_runs: 1


sampling_dirichlet: false
dirichlet_alpha: 0.5

save_model: true
save_on_epochs: [1]
is_poison: false
record_local_train: false
resumed_model: false
resumed_model_name: ''
resumed_model_path: ''



