type: mnist
lr: 0.02
momentum: 0.9
decay: 0.0005
batch_size: 60
test_batch_size: 50
epochs: 5
internal_epochs: 10 
binary_cls: true  

withDP: true
max_clip_norm: 0.7 
noise_multiplier: 2.5
delta: 0.0029  
no_models: 20
number_of_total_participants: 200
pre_path: saved_models/mnist_backdoor
n_runs: 1

dpfl: max_model               #  median_per_layer; max_per_layer; max_model; median_model
fl_aggregation: 'fedavg'      # rfa, krum, mkrum, bulyan, median, trmean
sampling_dirichlet: false
dirichlet_alpha: 0.5



is_poison: true
num_adv: 10
dba: false
adv_method: 'backdoor'  # labelflip, backdoor
scale_factor: 50 
random_vector_noise: 1000
random_additive_noise: 3
poisoning_per_batch: 60 # full batch
poison_label_swap: 0
poison_pattern: [[23,26],[23,27],  
                  [24,26],[24,27],
                  [25,25],[25,26],[25,26],
                  [26,24],[26,25],[26,26],[26,27],
                  [27,23],[27,24],[27,25],[27,26],[27,27]
                  ]


record_p: false
record_local_train: false


save_model: false
save_on_epochs: [1]

resumed_model: false
resumed_model_name: ''
resumed_model_path: ''




